// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY-xpd3T2qMXGlyTKE1GxwXqfMJQwM6p4',
    appId: '1:816353500473:web:99a35fbc80429529dddce8',
    messagingSenderId: '816353500473',
    projectId: 'mental-heath-care',
    authDomain: 'mental-heath-care.firebaseapp.com',
    storageBucket: 'mental-heath-care.appspot.com',
    measurementId: 'G-EJ57C6BWRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG7aWnHnm3X5yHKNFUP1fN3_G3nCKYndw',
    appId: '1:816353500473:android:94c58c0808b9b953dddce8',
    messagingSenderId: '816353500473',
    projectId: 'mental-heath-care',
    storageBucket: 'mental-heath-care.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9APCG0r5sdz1kwDHAACgeOMm-Pbm1bMM',
    appId: '1:816353500473:ios:f01865af49561daedddce8',
    messagingSenderId: '816353500473',
    projectId: 'mental-heath-care',
    storageBucket: 'mental-heath-care.appspot.com',
    iosClientId: '816353500473-c1p9ejkp60hqvb08r315d9oi1hb6f562.apps.googleusercontent.com',
    iosBundleId: 'com.kosidev.mentalHealthCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9APCG0r5sdz1kwDHAACgeOMm-Pbm1bMM',
    appId: '1:816353500473:ios:9bbe83291ff8171adddce8',
    messagingSenderId: '816353500473',
    projectId: 'mental-heath-care',
    storageBucket: 'mental-heath-care.appspot.com',
    iosClientId: '816353500473-jrpm1uvhu5gj75q82bavepnr8gr8qr8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentalHealthCareApp',
  );
}
